id = "papercolor"
name = "PaperColor"
description = "A clean, light theme inspired by the texture of paper"
version = "0.1.0"
schema_version = 1
authors = ["Your Name <your.email@example.com>"]
repository = "https://github.com/yourusername/papercolor-zed"

[themes]
path = "themes"
