id = "papercolor"
name = "PaperColor"
description = "The original PaperColor Theme, inspired by Google Material Design, ported to Zed."
version = "0.1.0"
schema_version = 1
authors = ["Lewin Probst <info@emirror.de>"]
repository = "https://github.com/emirror-de/papercolor-zed"
