id = "papercolor"
name = "PaperColor"
description = "A clean, light theme inspired by the texture of paper"
version = "0.1.0"
schema_version = 1
authors = ["Lewin Probst <info@emirror.de>"]
repository = "https://github.com/emirror-de/papercolor-zed"
